backbone_network:
  name: 'looped_vit'
  embed_dim: 256  # 384 for small, 768 for base; note that this should be divisible by the number of heads
  num_heads: 8  # 8
  mlp_ratio: 4  # used instead of explicit ff_dim
  qkv_bias: true
  num_layers: 1 # number of non-tied layers
  num_loops: 6  # number of loops if non-pondering
  ape_dropout_rate: 0.0
  attn_dropout_rate: 0.1
  attn_proj_dropout_rate: 0.0
  ff_dropout_rate: 0.1
  init_weights_cfg:
    type: 'xavier'  # choices: 'xavier', 'kaiming', 'trunc_normal', 'normal'
    distribution: 'uniform' # choices: 'uniform', 'normal'; applies if type is 'xavier' or 'kaiming'