backbone_network:
  name: 'vit'
  embed_dim: 128  # 384 for small, 768 for base; note that this should be divisible by the number of heads
  num_heads: 8  # 8
  mlp_ratio: 4  # used instead of explicit ff_dim
  qkv_bias: true
  num_layers: 8  # 12
  ape_dropout_rate: 0.25
  attn_dropout_rate: 0.25
  attn_proj_dropout_rate: 0.25
  ff_dropout_rate: 0.25
  init_weights_cfg:
    type: 'xavier'
    distribution: 'uniform'