backbone_network:
  name: 'resnet'
  network_size: null  # choices: 18 (for ResNet18), 50 (for ResNet50), null for custom ResNet
  embed_dim: 128  # 384; this is the output dimension (i.e., number of channels) of the backbone network