backbone_network:
  name: 'vit'
  embed_dim: 384  # 384 for small, 768 for base
  num_layers: 12
  num_heads: 8  # 12
  mlp_ratio: 4  # TODO: think of implementing the explicit relationship with ff_dim (used in Transformer)?
  qkv_bias: true