backbone_network:
  name: 'vit'
  embed_dim: 128  # 384 for small, 768 for base; note that this should be divisible by the number of heads
  num_heads: 4  # 8
  mlp_ratio: 4  # used instead of explicit ff_dim
  qkv_bias: true
  num_layers: 6  # 6
  ape_dropout_rate: 0.0
  attn_dropout_rate: 0.1  # 0.1
  attn_proj_dropout_rate: 0.0
  ff_dropout_rate: 0.1  # 0.1
  init_weights_cfg:
    type: 'trunc_normal'  # choices: 'xavier', 'kaiming', 'trunc_normal', 'normal'
    distribution: 'uniform' # choices: 'uniform', 'normal'; applies if type is 'xavier' or 'kaiming'