backbone_network:
  name: 'vit'
  embed_dim: 384  # 64 (for 100k params), 128 (for 1M params), 384 (for 10M params), 384 (for 20M params); 384 for small, 768 for base; note that this should be divisible by the number of heads
  num_heads: 8  # 2 (for 100k params), 4 (for 1M params), 8 (for 10M params), 8 (for 20M params)
  mlp_ratio: 4  # used instead of explicit ff_dim
  qkv_bias: true
  num_layers: 6  # 2 (for 100k params), 6 (for 1M params), 6 (for 10M params), 12 (for 20M params); number of layers
  ape_dropout_rate: 0.0
  attn_dropout_rate: 0.1  # 0.1
  attn_proj_dropout_rate: 0.0
  ff_dropout_rate: 0.1  # 0.1
  init_weights_cfg:
    type: 'trunc_normal'  # choices: 'xavier', 'kaiming', 'trunc_normal', 'normal'
    distribution: 'uniform' # choices: 'uniform', 'normal'; applies if type is 'xavier' or 'kaiming'