data:
  dataset_dir: './${base.data_env}/final_datasets/${experiment.study}/${experiment.setting}/${experiment.name}'
  num_workers: 4
  train_batch_size: 32
  val_batch_size: 50
  test_batch_size: 50
  transform:
    enabled: true # whether to apply data transformation (e.g., normalization, augmentation). TODO: We can add a field to specify the type of transformation
  use_gen_test_set: false
  test_in_and_out_domain: false