data_module: 'CVRDataModule'
dataset_dir: './CVR/final_datasets/compositionality/exp_setting_1/experiment_2'  # ./CVR/final_datasets/sample-efficiency/exp_setting_1/experiment_3
num_workers: 4
train_batch_size: 32
val_batch_size: 50
test_batch_size: 50
train_transform: null
test_transform: null
use_gen_test_set: false
test_in_and_out_domain: false