experiment:
  experiments_dir: './${base.data_env}/experiments'
  study: 'compositionality'  # choices: 'sample-efficiency', 'sys-gen', 'compositionality'
  setting: 'exp_setting_1'  # depends on the study
  name: 'experiment_1'  # depends on the study and setting
  exp_summary_results_dir: '${experiment.experiments_dir}/exp_summary_results'
  exp_logger: 'wandb'