model_module: 'CVRModel'  # it can be: CVRModel, REARCModel, BEFOREARCModel
model_backbone: 'vanilla_vit_base'  # it can be: vanilla_vit_base, resnet18, resnet50
pretrained: null
use_task_embeddings: true
mlp_dim: 256  # 128
mlp_hidden_dim: 2048
activation: 'relu'
use_batchnorm: false
optimizer: 'Adam' # it can be: Adam, AdamW, SGD
scheduler: 'ReduceLROnPlateau' # it can be: ReduceLROnPlateau, StepLR, MultiStepLR, ExponentialLR, CosineAnnealingLR
lr: 0.001
wd: 0.001