# NOTE: The parameters structure should follow that of the nested keys used in the config files in /configs by using "parameters" to create imbrication

# Program to run
program: experiment.py

# Method to use for HPs optimization: random, grid, bayes
method: grid

# Project of the sweep
# project: 'VisReas-project'
# entity: 'klim-t'

# Metric to optimize
metric:
  goal: minimize
  name: metrics/val_loss_epoch  # TODO: see why metrics/val_loss does not exist in the Sweep section on WandB

##### Experiment sweep #####
parameters:
  experiment:
    parameters:
      study:
        # values: ['sample-efficiency']
        # values: ['compositionality']
        values: ['sys-gen']
      setting:
        # values: ['exp_setting_1'] # sample-efficiency
        # values: ['exp_setting_1', 'exp_setting_2', 'exp_setting_3', 'exp_setting_5']  # compositionality
        values: ['exp_setting_1', 'exp_setting_2']  # sys-gen
      name:
        # values: ['experiment_1', experiment_2', 'experiment_3', 'experiment_4', 'experiment_5', 'experiment_6', 'experiment_7', 'experiment_8', 'experiment_9', 'experiment_10', 'experiment_11', 'experiment_12', 'experiment_13', 'experiment_14', 'experiment_15', 'experiment_16']  # sample-efficiency
        # values: []  # compositionality; the number of experiments per setting is not the same across settings
        values: ['experiment_1', 'experiment_2']  # sys-gen        

##### Hyperparameters sweep #####


# early_terminate:
#   type: hyperband
#   s: 2
#   eta: 3
#   max_iter: 10