# NOTE: The parameters structure should follow that of the nested keys used in the config files in /configs by using "parameters" to create imbrication

# Program to run
program: experiment.py

# Method to use for HPs optimization: random, grid, bayes
method: grid

# Project of the sweep
# project: 'VisReas-project'
# entity: 'klim-t'  # 'VisReas-ETHZ'

# Metric to optimize
metric:
  goal: minimize
  name: metrics/gen_val_loss_epoch     

##### Hyperparameters sweep #####
parameters:
  model:
    parameters:
      
      pondernet:
        parameters:
          max_steps:
            values: [5, 10, 20]         # number of steps for the PonderNet
          beta:
            values: [0.01, 0.1, 0.2]    # KLD regularization coefficient
          lambda_p:
            values: [0.05, 0.1]         # expected value for the number of steps/iterations
          epsilon:
            values: [0.01, 0.05, 0.1]   # to stop when the cumulative probability mass is greater than epsilon

      visual_tokens:
        parameters:
          enabled:
            values: [true, false]  # whether to use visual tokens or not
      
      ape:
        parameters:
          enabled:
            values: [true, false]  # whether to use absolute positional encoding or not
      
      rpe:
        parameters:
          enabled:
            values: [true, false]  # whether to use relative positional encoding or not
      

# early_terminate:
#   type: hyperband
#   s: 2
#   eta: 3
#   max_iter: 10